### PR TITLE
Added option to provide a PreferredDataLocation for supporting multi-geo tenants

### PR DESCRIPTION
**Pull request by KoenZomers**
| Q               | A
| --------------- | ---
| Bug fix?        | no
| New feature?    | yes
| New sample?      | no
| Related issues?  | asked for in i.e. https://github.com/pnp/PnP-PowerShell/issues/2682

#### What's in this Pull Request?

Added PreferredDataLocation parameter to creating a new site which allows for specifying of a geographical region for multi-geo enabled tenants.

Also added fix for forcing sensitivitylabel to use the SharePoint API to create the site, otherwise the sensitivity label will not be applied.

### CODE REVIEW

**Comment by TroyHostetter** [comment]
I copied the files into version 3.21.2005.1 folder and get this error when i load the psd1

Import-Module : Could not load file or assembly 'file:///D:\temp\SharePointPnPPowerShellOnlineFix\3.21.2005.1\SharePointPnP.PowerShell.Online.Commands.dll' or one of its dependencies. Operation is not supported. (Exception from HRESULT: 
0x80131515)
At line:3 char:1
+ Import-Module (Get-ChildItem D:\temp\SharePointPnPPowerShellOnlineFix ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotSpecified: (:) [Import-Module], FileLoadException
    + FullyQualifiedErrorId : System.IO.FileLoadException,Microsoft.PowerShell.Commands.ImportModuleCommand

**Comment by KoenZomers** [comment]
Did you also copy in the existing files of PnP PowerShell? The files I have shared are just a subset, not an entire release. So you would need to copy them over an existing PnP PowerShell release.

**Comment by TroyHostetter** [comment]
Yes.  I took the version I had specified and copied all the files into it, overwriting what was there.

-Troy

**Comment by TroyHostetter** [comment]
I just did another “Save-Module -Name SharePointPnPPowerShellOnline” and got version 3.21.2005.2 .. still the same error:

[cid:image001.png@01D63B2B.CDAB33B0]

-Troy

**Comment by KoenZomers** [comment]
@TroyHostetter not sure why it fails to load for you. [Someone else managed to test it](https://github.com/pnp/PnP-PowerShell/issues/2682#issuecomment-639620450) against a multi geo enabled tenant and it works. Will proceed with submitting this PR so it can hopefully still make it in next Tuesdays release.

**Comment by TroyHostetter** [comment]
If it worked for someone else then no need to wait for me 😊

Thanks.  BTW .. my issue was not in creating sites but executing Set-PnPHubSite .. that threw the error.

-Troy

**Pull request merged**
