### PR TITLE
Teams object handler: Make Team properties optional to fix JSON parsing

### PR DESCRIPTION
**Pull request by heinrich-ulbricht**
| Q               | A
| --------------- | ---
| Bug fix        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | N/A

#### What's in this Pull Request?

Using `Get-PnPTenantTemplate` to export a Team failed for me since some values where `null` in the resulting Teams data:

image

This caused the JSON parsing to fail here:

https://github.com/pnp/PnP-Sites-Core/blob/edae8152c0a04dd0fe90a30921ab95a5bfa435fe/Core/OfficeDevPnP.Core/Framework/Provisioning/ObjectHandlers/ObjectTeams.cs#L1417

Making them optional (as they seem to be optional) fixes this error.

### CODE REVIEW

**Comment by gautamdsheth** [comment]
Yo , check this out 😊

https://github.com/pnp/PnP-Sites-Core/pull/2715

**Comment by heinrich-ulbricht** [comment]
Darn, a month too late 😅 Just learned there is a merge freeze... things will be stacking up. I'll close this one then.

**Comment by heinrich-ulbricht** [comment]
And you @gautamdsheth are a force to be reckoned with 😄 I should check your PRs first in the future before opening one. You are doing a lot of good things.

**Comment by gautamdsheth** [comment]
Oh wow !!! Thank you @heinrich-ulbricht  for your kind words 😍 🙏🏼, you are an inspiration yourself !

**Pull request closed without merging**
