### PR TITLE
Anglesharp

### LINKED ISSUE #2378: Does not work with AngleSharp 0.12.1
Hi guys,

I have a ClientSidePages section that fails to work after upgrade of NuGet packages. Error is:

03/03 - ClientSidePages
Failed to apply template: Could not load type 'AngleSharp.Parser.Html.HtmlParserOptions' from assembly 'AngleSharp, Version=0.12.1.0, Culture=neutral, PublicKeyToken=e83494dcdc6d31ea'.

Anything I have to do or is it you ?

### PR DESCRIPTION
**Pull request by netclectic**
| Q               | A
| --------------- | ---
| Bug fix?        | yes
| New feature?    | no
| New sample?      | no
| Related issues?  | fixes #2378, partially #2647

#### What's in this Pull Request?

Updates the AngleSharp package to the latest v0.14 and fixes related usage of parser in ClientSidePage classes

### CODE REVIEW

**Comment by jansenbe** [comment]
Hi @netclectic , this package will be deprecated soon in favor of [PnP Framework](https://github.com/pnp/pnpframework). In PnP Framework we've already upgraded to the latest AngleSharp, so I would encourage you to try that package instead of this going forward.

**Comment by netclectic** [comment]
Hi @jansenbe, I've started testing with PnP Framework and it looks promising but sadly I have to also support some legacy software that will likely not be able to update.

**Comment by jansenbe** [comment]
I'll then also merge this one into PnP Sites Core

**Comment by jansenbe** [comment]
Manually merged this one, you're referenced as author in the changelog. Thanks for sharing

**Pull request closed without merging**
